# Generated by Django 3.0.5 on 2020-05-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('word', models.CharField(max_length=30)),
                ('defination', models.CharField(max_length=60)),
                ('example', models.CharField(max_length=90)),
            ],
        ),
    ]
